//! A single scalar value, used for literals, parameters, and per-cell access out
//! of columns. The columnar store (see `column.zig`) is the hot path; `Value` is
//! the boxed, one-at-a-time view used at cold edges and in tests.
//!
//! `Decimal` is exact, `unscaled * 10^-scale`. Its i128 field is `align(8)` on
//! purpose: natural 16-byte alignment would size the whole `Value` union at 48
//! bytes, so every bool and i64 would pay for a decimal it does not hold; relaxed,
//! `Value` is 32 bytes, and x86 handles the unaligned access on a cold path.
//!
//! `pow10_table` lives here because both `column` and `eval` depend on this module.
//! It is generated by the repeated multiplication the old runtime loop did, so each
//! entry is bit-identical to what that loop returned; it exists because
//! `keyhash.hashValue` folds every decimal key through `Decimal.toF64` per row.
//!
//! `Threshold` is the live top-N bound shared between a TopN operator and a source
//! that can skip blocks (currently parquet). The operator publishes the K-th value;
//! a source skips regions whose statistics prove they hold nothing better. Until
//! `full` (the heap holds K entries) every region can contribute, and comparisons
//! must be strict, since a region whose extreme equals the bound may hold ties.

const std = @import("std");

pub const Decimal = struct {
    unscaled: i128 align(8),
    scale: u8,

    pub fn toF64(self: Decimal) f64 {
        return @as(f64, @floatFromInt(self.unscaled)) / pow10f(self.scale);
    }
};

const pow10_table = blk: {
    var t: [39]f64 = undefined;
    var r: f64 = 1;
    for (&t) |*e| {
        e.* = r;
        r *= 10;
    }
    break :blk t;
};

pub fn pow10f(n: u8) f64 {
    if (n < pow10_table.len) return pow10_table[n];
    var r: f64 = pow10_table[pow10_table.len - 1];
    var k: u8 = pow10_table.len - 1;
    while (k < n) : (k += 1) r *= 10;
    return r;
}

pub const Threshold = struct {
    column: []const u8 = "",
    desc: bool = false,
    full: bool = false,
    value: Value = .null,
};

pub const Value = union(enum) {
    null,
    bool: bool,
    int: i64,
    float: f64,
    decimal: Decimal,
    string: []const u8,
    bytes: []const u8,
    date: i32,
    time: i64,
    timestamp: i64,

    pub fn isNull(self: Value) bool {
        return self == .null;
    }
};

test "value tag and null" {
    const v: Value = .{ .int = 7 };
    try std.testing.expect(!v.isNull());
    try std.testing.expectEqual(@as(i64, 7), v.int);

    const n: Value = .null;
    try std.testing.expect(n.isNull());
}
