//! End-to-end benchmark harness (`zig build bench-e2e`).
//!
//! `bench.zig` gates the SIMD kernels; this gates the *engine*. It runs committed
//! scripts through the real CLI, times the whole pipeline, and — where a DuckDB
//! reference exists — checks the answer as well as the clock. Two suites:
//!
//!   tpch-*   compute: scan, filter, join, GROUP BY, sort. What DuckDB is good at.
//!   move-*   movement: read every row, serialise every row, write it. What basalt
//!            is *for*, and what no analytics benchmark measures.
//!
//! Both engines write a CSV sink, so a comparison is whole-pipeline rather than
//! basalt-writes-a-file versus duckdb-prints-a-table.
//!
//! Fixtures are TPC-H SF1, generated by `bench/gen.sql` — see `bench/README.md`.
//! They are NOT committed (≈1.3 GB). Point the harness at them with `--data` or
//! `BASALT_BENCH_DATA`.
//!
//! Timing is wall clock of the child process, so it includes CLI startup. That is
//! the honest number for a movement tool, but it is a fixed tax that matters at
//! small scale, so the harness measures each engine's startup and prints it.

const std = @import("std");

const Suite = enum { tpch, movement };

const Query = struct {
    name: []const u8,
    suite: Suite,
    script: []const u8,
    /// DuckDB equivalent, or null where no meaningful reference exists (the movement
    /// scripts have no compute to compare, only throughput).
    ref: ?[]const u8,
};

const queries = [_]Query{
    .{ .name = "tpch-q01", .suite = .tpch, .script = "bench/tpch/q01.sql", .ref = "bench/reference/q01.sql" },
    .{ .name = "tpch-q03", .suite = .tpch, .script = "bench/tpch/q03.sql", .ref = "bench/reference/q03.sql" },
    .{ .name = "tpch-q06", .suite = .tpch, .script = "bench/tpch/q06.sql", .ref = "bench/reference/q06.sql" },
    .{ .name = "tpch-q12", .suite = .tpch, .script = "bench/tpch/q12.sql", .ref = "bench/reference/q12.sql" },
    .{ .name = "tpch-q14", .suite = .tpch, .script = "bench/tpch/q14.sql", .ref = "bench/reference/q14.sql" },
    .{ .name = "move-m01", .suite = .movement, .script = "bench/movement/m01_parquet_to_csv.sql", .ref = null },
    .{ .name = "move-m02", .suite = .movement, .script = "bench/movement/m02_csv_to_csv.sql", .ref = null },
    .{ .name = "move-m03", .suite = .movement, .script = "bench/movement/m03_csv_filtered.sql", .ref = null },
};

/// Relative tolerance when both sides parse as a number. Float SUM order differs
/// between engines, so bit-equality is the wrong bar; a real regression moves a
/// result far more than this.
const tolerance = 1e-9;

const Opts = struct {
    data: []const u8,
    out: []const u8 = "/tmp/basalt-bench-out",
    bin: []const u8 = "zig-out/bin/basalt",
    reps: usize = 3,
    json: bool = false,
    filter: ?[]const u8 = null,
};

const Timing = struct {
    min_ms: u64 = 0,
    med_ms: u64 = 0,
    failed: bool = false,
    /// First line of stderr when a run fails, for the report.
    err: []const u8 = "",
};

const Result = struct {
    q: Query,
    basalt: Timing = .{},
    duck: ?Timing = null,
    rows: usize = 0,
    /// null when checked and equal, a message when not, "" when unchecked.
    mismatch: ?[]const u8 = "",
};

fn usage(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\usage: zig build bench-e2e -- [options]
        \\
        \\  --data <dir>    TPC-H SF1 fixtures (or $BASALT_BENCH_DATA). See bench/README.md.
        \\  --out <dir>     scratch for sink output (default /tmp/basalt-bench-out; use a tmpfs)
        \\  --bin <path>    basalt binary (default zig-out/bin/basalt — build ReleaseFast first!)
        \\  --reps <n>      timed runs per query after one warmup (default 3)
        \\  --filter <s>    only queries whose name contains <s>
        \\  --json          emit JSON instead of a table
        \\
    );
}

/// Run argv, return wall-clock nanoseconds. `term` non-zero is reported, not fatal:
/// one query failing should not hide the rest of the table.
fn timeRun(a: std.mem.Allocator, argv: []const []const u8, out_err: *[]const u8) !?u64 {
    var timer = try std.time.Timer.start();
    const res = std.process.Child.run(.{ .allocator = a, .argv = argv }) catch |e| {
        out_err.* = @errorName(e);
        return null;
    };
    const ns = timer.read();
    defer a.free(res.stdout);
    const ok = switch (res.term) {
        .Exited => |c| c == 0,
        else => false,
    };
    if (!ok) {
        // Keep the first stderr line; the rest is noise in a table.
        const nl = std.mem.indexOfScalar(u8, res.stderr, '\n') orelse res.stderr.len;
        out_err.* = res.stderr[0..nl];
        return null;
    }
    a.free(res.stderr);
    return ns;
}

fn measure(a: std.mem.Allocator, argv: []const []const u8, reps: usize) !Timing {
    var t = Timing{};
    // Warmup: fills the page cache so we measure the engine, not the first read of
    // a 200 MB file. Every rep below then sees the same warm state.
    var err: []const u8 = "";
    if (try timeRun(a, argv, &err) == null) return .{ .failed = true, .err = err };

    const samples = try a.alloc(u64, reps);
    defer a.free(samples);
    for (samples) |*s| {
        const ns = try timeRun(a, argv, &err) orelse return .{ .failed = true, .err = err };
        s.* = ns / std.time.ns_per_ms;
    }
    std.mem.sort(u64, samples, {}, std.sort.asc(u64));
    t.min_ms = samples[0];
    t.med_ms = samples[samples.len / 2];
    return t;
}

/// Compare two CSV files field by field: numeric where both sides parse, exact bytes
/// otherwise. Returns null when equal, else a caller-owned description of the first
/// difference — the point being that a fast wrong answer is not a result.
fn compareCsv(a: std.mem.Allocator, want_path: []const u8, got_path: []const u8) !?[]const u8 {
    const max = 64 * 1024 * 1024;
    const want = std.fs.cwd().readFileAlloc(a, want_path, max) catch |e|
        return try std.fmt.allocPrint(a, "reference unreadable: {s}", .{@errorName(e)});
    const got = std.fs.cwd().readFileAlloc(a, got_path, max) catch |e|
        return try std.fmt.allocPrint(a, "output unreadable: {s}", .{@errorName(e)});

    var wl = std.mem.tokenizeScalar(u8, want, '\n');
    var gl = std.mem.tokenizeScalar(u8, got, '\n');
    var line: usize = 0;
    while (true) {
        const w = wl.next();
        const g = gl.next();
        if (w == null and g == null) return null;
        line += 1;
        if (w == null) return try std.fmt.allocPrint(a, "line {d}: extra output row", .{line});
        if (g == null) return try std.fmt.allocPrint(a, "line {d}: missing output row", .{line});

        var wf = std.mem.splitScalar(u8, std.mem.trimRight(u8, w.?, "\r"), ',');
        var gf = std.mem.splitScalar(u8, std.mem.trimRight(u8, g.?, "\r"), ',');
        var col: usize = 0;
        while (true) {
            const wv = wf.next();
            const gv = gf.next();
            if (wv == null and gv == null) break;
            col += 1;
            if (wv == null or gv == null)
                return try std.fmt.allocPrint(a, "line {d}: column count differs", .{line});
            if (std.mem.eql(u8, wv.?, gv.?)) continue;
            const wn = std.fmt.parseFloat(f64, wv.?) catch {
                return try std.fmt.allocPrint(a, "line {d} col {d}: want `{s}`, got `{s}`", .{ line, col, wv.?, gv.? });
            };
            const gn = std.fmt.parseFloat(f64, gv.?) catch {
                return try std.fmt.allocPrint(a, "line {d} col {d}: want `{s}`, got `{s}`", .{ line, col, wv.?, gv.? });
            };
            const scale = @max(@abs(wn), @abs(gn));
            const diff = @abs(wn - gn);
            if (diff > tolerance * @max(scale, 1.0))
                return try std.fmt.allocPrint(a, "line {d} col {d}: want {d}, got {d}", .{ line, col, wn, gn });
        }
    }
}

fn countRows(a: std.mem.Allocator, path: []const u8) usize {
    const txt = std.fs.cwd().readFileAlloc(a, path, 4 * 1024 * 1024 * 1024) catch return 0;
    defer a.free(txt);
    var n: usize = 0;
    for (txt) |c| {
        if (c == '\n') n += 1;
    }
    return if (n > 0) n - 1 else 0; // minus the header
}

/// `duckdb -c` with @DATA@/@OUT@ filled in. Absent duckdb just means no reference
/// column, not a failed benchmark.
fn duckSql(a: std.mem.Allocator, ref: []const u8, data: []const u8, out: []const u8) ![]const u8 {
    const src = try std.fs.cwd().readFileAlloc(a, ref, 1024 * 1024);
    defer a.free(src);
    const with_data = try std.mem.replaceOwned(u8, a, src, "@DATA@", data);
    defer a.free(with_data);
    return std.mem.replaceOwned(u8, a, with_data, "@OUT@", out);
}

pub fn main() !void {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer _ = gpa.deinit();
    var arena_state = std.heap.ArenaAllocator.init(gpa.allocator());
    defer arena_state.deinit();
    const a = arena_state.allocator();

    var out_buf: [8192]u8 = undefined;
    var out_file = std.fs.File.stdout().writer(&out_buf);
    const w = &out_file.interface;
    defer w.flush() catch {};

    const argv = try std.process.argsAlloc(a);
    var opts = Opts{ .data = "" };
    var i: usize = 1;
    while (i < argv.len) : (i += 1) {
        const arg = argv[i];
        const val = struct {
            fn next(list: [][:0]u8, idx: *usize) ?[]const u8 {
                if (idx.* + 1 >= list.len) return null;
                idx.* += 1;
                return list[idx.*];
            }
        }.next;
        if (std.mem.eql(u8, arg, "--data")) {
            opts.data = val(argv, &i) orelse return usage(w);
        } else if (std.mem.eql(u8, arg, "--out")) {
            opts.out = val(argv, &i) orelse return usage(w);
        } else if (std.mem.eql(u8, arg, "--bin")) {
            opts.bin = val(argv, &i) orelse return usage(w);
        } else if (std.mem.eql(u8, arg, "--filter")) {
            opts.filter = val(argv, &i) orelse return usage(w);
        } else if (std.mem.eql(u8, arg, "--reps")) {
            opts.reps = std.fmt.parseInt(usize, val(argv, &i) orelse return usage(w), 10) catch return usage(w);
        } else if (std.mem.eql(u8, arg, "--json")) {
            opts.json = true;
        } else {
            try usage(w);
            return;
        }
    }
    if (opts.data.len == 0) {
        opts.data = std.process.getEnvVarOwned(a, "BASALT_BENCH_DATA") catch {
            try w.writeAll("error: no fixtures. Pass --data <dir> or set BASALT_BENCH_DATA.\n" ++
                "       Generate them once with:  duckdb tpch.db < bench/gen.sql   (see bench/README.md)\n");
            return;
        };
    }
    if (opts.reps == 0) opts.reps = 1;

    std.fs.cwd().makePath(opts.out) catch {};

    // Startup tax, reported so a small-result query's number can be read honestly.
    var serr: []const u8 = "";
    const duck_boot = try timeRun(a, &.{ "duckdb", "-c", "SELECT 1" }, &serr);
    const have_duck = duck_boot != null;

    var results = std.array_list.Managed(Result).init(a);
    for (queries) |q| {
        if (opts.filter) |f| {
            if (std.mem.indexOf(u8, q.name, f) == null) continue;
        }
        if (!opts.json) {
            try w.print("running {s} ...\r", .{q.name});
            try w.flush();
        }
        var r = Result{ .q = q };

        const b_out = try std.fmt.allocPrint(a, "{s}/{s}-basalt", .{ opts.out, q.name });
        r.basalt = try measure(a, &.{
            opts.bin,          "run", q.script,
            "-p",              try std.fmt.allocPrint(a, "data={s}", .{opts.data}),
            "-p",              try std.fmt.allocPrint(a, "out={s}", .{b_out}),
            "--quiet",
        }, opts.reps);

        const b_csv = try std.fmt.allocPrint(a, "{s}.csv", .{b_out});
        if (!r.basalt.failed) r.rows = countRows(a, b_csv);

        if (q.ref) |ref| {
            if (have_duck) {
                const d_csv = try std.fmt.allocPrint(a, "{s}/{s}-duckdb.csv", .{ opts.out, q.name });
                const sql = try duckSql(a, ref, opts.data, d_csv);
                r.duck = try measure(a, &.{ "duckdb", "-c", sql }, opts.reps);
                if (!r.basalt.failed and !r.duck.?.failed)
                    r.mismatch = try compareCsv(a, d_csv, b_csv);
            }
        }
        try results.append(r);
    }

    if (opts.json) {
        try w.writeAll("{\"results\":[");
        for (results.items, 0..) |r, n| {
            if (n > 0) try w.writeAll(",");
            try w.print(
                "{{\"query\":\"{s}\",\"suite\":\"{s}\",\"basalt_min_ms\":{d},\"basalt_med_ms\":{d}",
                .{ r.q.name, @tagName(r.q.suite), r.basalt.min_ms, r.basalt.med_ms },
            );
            if (r.duck) |d| try w.print(",\"duckdb_min_ms\":{d},\"duckdb_med_ms\":{d}", .{ d.min_ms, d.med_ms });
            try w.print(",\"rows\":{d},\"ok\":{}", .{ r.rows, r.mismatch == null or r.mismatch.?.len == 0 });
            try w.writeAll("}");
        }
        try w.writeAll("]}\n");
        return;
    }

    try w.print("\nend-to-end bench   reps={d} (min of), fixtures={s}\n", .{ opts.reps, opts.data });
    try w.print("duckdb startup tax {d} ms{s}\n\n", .{
        if (duck_boot) |d| d / std.time.ns_per_ms else 0,
        if (have_duck) "" else "  (duckdb not on PATH — no reference column)",
    });
    try w.writeAll("query      suite      basalt    duckdb     ratio   rows  result\n");
    try w.writeAll("---------- --------- ------- --------- --------- ------ ----------------------------\n");
    for (results.items) |r| {
        try w.print("{s:<10} {s:<9} ", .{ r.q.name, @tagName(r.q.suite) });
        if (r.basalt.failed) {
            try w.print("{s:>7} ", .{"FAIL"});
        } else {
            try w.print("{d:>5}ms ", .{r.basalt.min_ms});
        }
        if (r.duck) |d| {
            if (d.failed) {
                try w.print("{s:>9} {s:>9} ", .{ "FAIL", "-" });
            } else {
                try w.print("{d:>7}ms ", .{d.min_ms});
                if (r.basalt.failed or d.min_ms == 0) {
                    try w.print("{s:>9} ", .{"-"});
                } else {
                    const ratio = @as(f64, @floatFromInt(r.basalt.min_ms)) / @as(f64, @floatFromInt(d.min_ms));
                    try w.print("{d:>8.2}x ", .{ratio});
                }
            }
        } else {
            try w.print("{s:>9} {s:>9} ", .{ "-", "-" });
        }
        try w.print("{d:>6}  ", .{r.rows});
        if (r.basalt.failed) {
            try w.print("{s}\n", .{r.basalt.err});
        } else if (r.mismatch) |m| {
            try w.print("{s}\n", .{if (m.len == 0) "unchecked" else m});
        } else {
            try w.writeAll("ok\n");
        }
    }
    try w.writeAll("\nratio <1 means basalt is faster. `ok` = matched duckdb within " ++
        "1e-9 relative.\n");
}
